export const companyFields = [
  'IT sector',
  'Finance sector',
  'Healthcare sector',
];

export const currencies = [
  'US Dollar(USD) ',
  'Euro(EUR) ',
  'British Pound(GBP) ',
  'Japanese Yen(JPY) ',
  'Australian Dollar(AUD) ',
  'Canadian Dollar(CAD) ',
  'Swiss Franc(CHF) ',
  'Chinese Yuan(CNY) ',
  'Indian Rupee(INR) ',
  'Russian Ruble(RUB) ',
  'Brazilian Real(BRL) ',
  'South African Rand(ZAR) ',
  'New Zealand Dollar(NZD) ',
  'Singapore Dollar(SGD) ',
  'Hong Kong Dollar(HKD) ',
  'Swedish Krona(SEK) ',
  'Norwegian Krone(NOK) ',
  'Danish Krone(DKK) ',
  'South Korean Won(KRW) ',
  'United Arab Emirates Dirham(AED) ',
  'Saudi Riyal(SAR) ',
  'Mexican Peso(MXN) ',
  'Argentine Peso(ARS) ',
  'Chilean Peso(CLP) ',
  'Polish Złoty(PLN) ',
  'Turkish Lira(TRY) ',
  'Sri Lankan Rupee(LKR) ',
];
